# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sinatra", "~> 4.0"

gem "json", "~> 2.7"

gem "rack", "~> 3.1"

gem "rackup", "~> 2.1"

gem "sequel", "~> 5.84"
gem "sqlite3", "~> 2.1"
